services:
  ollama:
    build: 
      context: .
      dockerfile: ./Dockerfile.ollama
    container_name: ollama
    entrypoint: /tmp/entrypoint.sh
    # runtime: nvidia
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: all
    #           capabilities: [gpu]
    volumes:
      - ollamavolume:/root/.ollama
    ports:
      - "11434:11434"
volumes:
  ollamavolume: